package com.test.game.Manager
{
	import com.superkaka.Tools.Singleton;
	import com.superkaka.game.Const.GameConst;
	import com.superkaka.game.Loader.AssetsType;
	import com.superkaka.game.Manager.AssetsUrl;
	
	import flash.net.URLLoaderDataFormat;
	
	public class AssetsUrlManager extends Singleton
	{
		public function AssetsUrlManager()
		{
			super();
		}
		
		public static function getIns():AssetsUrlManager{
			return Singleton.getIns(AssetsUrlManager);
		}
		
		public function init() : void{
			AssetsUrl.JSON_DATA = JSON_DATA;
			AssetsUrl.ACTIONS = ACTIONS;
			AssetsUrl.PLAYER_DATA = PLAYER_DATA;
			AssetsUrl.assetVersion = assetVersion;
		}
		
		public static const JSON_DATA:Object = {
			url:GameConst.ASSETS_URL+ "data/data.swf",
				version:"V123",
				type:AssetsType.ZIP,
				context:null,
				dataFormat:URLLoaderDataFormat.BINARY
		}
		
		public static const ACTIONS:Object = {
			url:GameConst.ASSETS_URL+"data/ACTIONS.xml",
				version:"V123",
				type:AssetsType.XML,
				context:null,
				dataFormat:URLLoaderDataFormat.TEXT
		};
		
		public static const PLAYER_DATA:Object = {
			url:"Assets/PlayerData.json",
			version:"",
			type:AssetsType.XML,
				context:null,
				dataFormat:URLLoaderDataFormat.TEXT,
				noCache:true
		};
		
		public static const assetVersion:Object = {
			"View/AchieveView" : "V112",
			"View/BagView" : "V109",
			"View/BaGuaView" : "V111",
			"View/BossBattleBar" : "",
			"View/BossView" : "V110",
			"View/CongratulationView" : "V113",
			"View/DoubleDungeonView" : "V110",
			"View/DungeonMenu" : "V101",
			"View/EliteSelectView" : "V103",
			"View/EscortView" : "V112",
			"View/FashionCombineView" : "V114",
			"View/FirstChargeView" : "V112",
			"View/FunnyBossView" : "V123",
			"View/GameOverView" : "V104",
			"View/GameSettingView" : "V118",
			"View/GetBookView" : "",
			"View/GetFiveCardView" : "V102",
			"View/GetSkillBookView" : "V103",
			"View/GiftView" : "V123",
			"View/HeroFightView" : "V116",
			"View/HeroScriptView" : "V118",
			"View/ItemCombineView" : "V118",
			"View/JingMaiView" : "V114",
			"View/LevelInfoView" : "V118",
			"View/LevelUpView" : "",
			"View/MainMapView" : "V123",
			"View/MainUI" : "V123",
			"View/MarketView" : "V111",
			"View/MidAutumnView" : "V123",
			"View/MissionView" : "V123",
			"View/PassLevelView" : "V107",
			"View/PlayerKillingFightView" : "V107",
			"View/RoleDetailView" : "V118",
			"View/SelectPlayerView" : "V1001",
			"View/ShopView" : "V122",
			"View/SignInView" : "V105",
			"View/SkillView" : "V118",
			"View/SkillButtonSetView" : "V118",
			"View/SkillUpView" : "V103",
			"View/SoundSettingView" : "V101",
			"View/startGameView" : "V1021",
			"View/StartPageView" : "V123",
			"View/StrengthenView" : "V118",
			"View/SummerGiftView" : "V114",
			"View/TipView" : "V113",
			"View/TitleView" : "V120",
			"View/UpdateInfoView" : "V106",
			"View/VipView" : "V118",
			"View/WeatherSelectView" : "V119",
			
			"Map/FunnyMap" : "V123",
			"Map/HeroMap" : "V116",
			"Map/Map1_1" : "",
			"Map/Map1_2" : "",
			"Map/Map1_3" : "",
			"Map/Map1_4" : "V103",
			"Map/MapBg1" : "",
			"Map/MapHideBg1" : "V103",
			"Map/Map2_1" : "",
			"Map/Map2_2" : "",
			"Map/Map2_3" : "",
			"Map/Map2_4" : "V105",
			"Map/MapBg2" : "",
			"Map/Map3_1" : "V108",
			"Map/Map3_2" : "V108",
			"Map/Map3_3" : "V108",
			"Map/Map3_4" : "V115",
			"Map/MapBg3" : "V108",
			"Map/MapHideBg3" : "V115",
			"Map/Map4_1" : "V117",
			"Map/Map4_2" : "V119",
			"Map/Map4_3" : "V121",
			"Map/MapBg4" : "V121",
			
			"Sound/BossFightSound" : "V1001",
			"Sound/ColdDownSound" : "",
			"Sound/CommonSound" : "",
			"Sound/KuangWuHitSound" : "",
			"Sound/LevelUpSound" : "",
			"Sound/MainMapSound" : "",
			"Sound/MoZhuLinFightSound" : "",
			"Sound/PassLevelSound" : "",
			"Sound/PlayerKillingSound" : "V107",
			"Sound/ReleaseSkillSound" : "",
			"Sound/StartPageSound" : "",
			"Sound/TaiXuGuanFightSound" : "",
			"Sound/WanEGuFightSound" : "V108",
			"Sound/WeatherBlackSound" : "V102",
			"Sound/WeatherRainSound" : "V102",
			"Sound/WeatherThunderSound" : "V111",
			"Sound/WeatherWindSound" : "V111",
			"Sound/XiaoYaoHitSound" : "",
			"Sound/NewGameCartoonSound" : "V112",
			"Sound/FengBoDuFightSound" : "V117",
			
			"Common/BuringCartoon" : "",
			"Common/Common" : "",
			"Common/DispositionUI" : "V111",
			"Common/DungeonUI" : "V122",
			"Common/FangZhengXingKai" : "",
			"Common/Effect" : "",
			"Common/FightEffect" : "",
			"Common/FirstLevelGuideView" : "V117",
			"Common/Guide" : "V116",
			"Common/HideMissionScene" : "V114",
			"Common/IconView" : "V123",
			"Common/InfoView" : "V116",
			"Common/Level" : "",
			"Common/LoadView" : "V114",
			"Common/NewGameCartoon" : "V112",
			"Common/PlayerKillingUI" : "V107",
			"Common/SkillCollision" : "V123",
			"Common/WeatherEffect" : "V102",
			
			"Animation/BiChiFuRenShowAnimation":"",
			"Animation/BuTongLaoRenShowAnimation":"",
			"Animation/ShiFangXiuCaiShowAnimation":"",
			"Animation/HongLianSanRenShowAnimation":"",
			"Animation/FengLiuDaoRenShowAnimation":"",
			"Animation/YinYangZhenRenShowAnimation":"",
			"Animation/JianMoWangHunShowAnimation":"V103",
			"Animation/MingHuoFenShenShowAnimation":"V105",
			"Animation/SeZhongEGuiShowAnimation":"V108",
			"Animation/LeiChenDianNuShowAnimation" : "V109",
			"Animation/ChiNanYuanNvShowAnimation" : "V110",
			"Animation/TanDeWuYanShowAnimation" : "V115",
			"Animation/TieJiangBaiDuShowAnimation" : "V117",
			"Animation/JueXiuJiaoQiaoShowAnimation" : "V119",
			"Animation/XiaoMianJunZiShowAnimation" : "V121",
			"Animation/FunnyBossOneShowAnimation" : "V123",
			"Animation/TuMeiShowAnimation" : "V123",
			"Animation/TuYeShowAnimation" : "V123",
			
			"Role/Title_1" : "V120",
			"Role/Title_2" : "V120",
			"Role/Title_3" : "V120",
			"Role/Title_4" : "V120",
			"Role/Title_5" : "V120",
			"Role/Title_6" : "V120",
			"Role/Title_7" : "V120",
			"Role/Title_8" : "V120",
			"Role/Title_9" : "V120",
			"Role/Title_10" : "V120",
			
			"Role/BiaoCheMuNiu" : "V112",
			"Role/BiaoCheLiuMa" : "V112",
			"Role/BiaoCheJinChe" : "V112",
			
			"Role/PKSpeedStatus" : "V107",
			"Role/PKAtkStatus" : "V107",
			"Role/MonsterAppear" : "",
			"Role/Relive" : "",
			"Role/BuringFront" : "",
			"Role/NoSkill" : "",
			"Role/HitEffect" : "",
			"Role/AutoFightEffect" : "V109",
			"Role/TemptationStatus" : "V119",
			
			"Role/KuangWu" : "",
			"Role/KuangWuCommonHit1" : "",
			"Role/KuangWuCommonHit2" : "",
			"Role/KuangWuCommonHit3" : "",
			"Role/KuangWuRunHit" : "",
			"Role/KuangWuPressHit" : "",
			"Role/KuangWuJumpPressHit1" : "V110",
			"Role/KuangWuJumpPressHit2" : "V110",
			"Role/KuangWuSkill1" : "",
			"Role/KuangWuSkill2_1" : "",
			"Role/KuangWuSkill2_2" : "",
			"Role/KuangWuSkill3" : "V103",
			"Role/KuangWuSkill4" : "",
			"Role/KuangWuSkill5" : "",
			"Role/KuangWuSkill6" : "",
			"Role/KuangWuSkill7_1" : "",
			"Role/KuangWuSkill7_2" : "",
			"Role/KuangWuSkill8_1" : "",
			"Role/KuangWuSkill8_2" : "",
			"Role/KuangWuSkill8_3" : "",
			"Role/KuangWuSkill8_4" : "",
			"Role/KuangWuSkill9" : "V103",
			"Role/KuangWuSkill10_1" : "",
			"Role/KuangWuSkill10_2" : "",
			"Role/KuangWuSkill10_3" : "",
			"Role/KuangWuSkill10_4" : "",
			"Role/KuangWuSkill7_2" : "",
			
			"Role/KuangWuHead" : "",
			"Role/KuangWuBackWeapon" : "",
			"Role/KuangWuClothes" : "",
			"Role/KuangWuFrontWeapon" : "",
			"Role/KuangWuHair" : "",
			"Role/KuangWuShoulder" : "",
			
			"Role/KuangWuBackWeapon01" : "",
			"Role/KuangWuClothes01" : "",
			"Role/KuangWuFrontWeapon01" : "",
			"Role/KuangWuHair01" : "",
			"Role/KuangWuShoulder01" : "",
			
			"Role/KuangWuHead02" : "V114",
			"Role/KuangWuBackWeapon02" : "",
			"Role/KuangWuClothes02" : "",
			"Role/KuangWuFrontWeapon02" : "",
			"Role/KuangWuShoulder02" : "",
			
			"Role/KuangWuHead03" : "V114",
			"Role/KuangWuBackWeapon03" : "",
			"Role/KuangWuClothes03" : "",
			"Role/KuangWuFrontWeapon03" : "",
			"Role/KuangWuShoulder03" : "",
			
			"Role/KuangWuHead04" : "V114",
			"Role/KuangWuHair04" : "V109",
			"Role/KuangWuBackWeapon04" : "V109",
			"Role/KuangWuClothes04" : "V109",
			"Role/KuangWuFrontWeapon04" : "V109",
			"Role/KuangWuShoulder04" : "V109",
			
			"Role/KuangWuHead05" : "V119",
			"Role/KuangWuHair05" : "V119",
			"Role/KuangWuBackWeapon05" : "V119",
			"Role/KuangWuClothes05" : "V119",
			"Role/KuangWuFrontWeapon05" : "V119",
			"Role/KuangWuShoulder05" : "V119",
			
			"Role/KuangWuHeadFashion01" : "V114",
			"Role/KuangWuHairFashion01" : "V110",
			"Role/KuangWuBackWeaponFashion01" : "V110",
			"Role/KuangWuClothesFashion01" : "V110",
			"Role/KuangWuFrontWeaponFashion01" : "V110",
			"Role/KuangWuShoulderFashion01" : "V110",
			
			"Role/KuangWuHeadFashion02" : "V114",
			"Role/KuangWuHairFashion02" : "V114",
			"Role/KuangWuBackWeaponFashion02" : "V114",
			"Role/KuangWuClothesFashion02" : "V114",
			"Role/KuangWuFrontWeaponFashion02" : "V114",
			"Role/KuangWuShoulderFashion02" : "V114",
			
			"Role/KuangWuHeadFashion03" : "V118",
			"Role/KuangWuHairFashion03" : "V118",
			"Role/KuangWuBackWeaponFashion03" : "V118",
			"Role/KuangWuClothesFashion03" : "V118",
			"Role/KuangWuFrontWeaponFashion03" : "V118",
			"Role/KuangWuShoulderFashion03" : "V118",
			
			"Role/KuangWuHeadFashion04" : "V118",
			"Role/KuangWuHairFashion04" : "V118",
			"Role/KuangWuBackWeaponFashion04" : "V118",
			"Role/KuangWuClothesFashion04" : "V118",
			"Role/KuangWuFrontWeaponFashion04" : "V118",
			"Role/KuangWuShoulderFashion04" : "V118",
			
			"Role/KuangWuHeadFashion05" : "V120",
			"Role/KuangWuHairFashion05" : "V120",
			"Role/KuangWuBackWeaponFashion05" : "V120",
			"Role/KuangWuClothesFashion05" : "V120",
			"Role/KuangWuFrontWeaponFashion05" : "V120",
			"Role/KuangWuShoulderFashion05" : "V120",
			
			"Role/KuangWuHeadFashion06" : "V122",
			"Role/KuangWuHairFashion06" : "V122",
			"Role/KuangWuBackWeaponFashion06" : "V122",
			"Role/KuangWuClothesFashion06" : "V122",
			"Role/KuangWuFrontWeaponFashion06" : "V122",
			"Role/KuangWuShoulderFashion06" : "V122",
			
			"Role/KuangWuCommonHit1Fashion01" : "V110",
			"Role/KuangWuCommonHit2Fashion01" : "V110",
			"Role/KuangWuCommonHit3Fashion01" : "V110",
			"Role/KuangWuRunHitFashion01" : "V110",
			"Role/KuangWuPressHitFashion01" : "V110",
			"Role/KuangWuJumpPressHit1Fashion01" : "V110",
			"Role/KuangWuJumpPressHit2Fashion01" : "V110",
			"Role/KuangWuSkill1Fashion01" : "V110",
			
			
			"Role/Sword" : "",
			"Role/XiaoYao" : "",
			"Role/XiaoYaoCommonHit1" : "",
			"Role/XiaoYaoCommonHit2" : "",
			"Role/XiaoYaoCommonHit3" : "",
			"Role/XiaoYaoCommonHit4" : "",
			"Role/XiaoYaoRunHit" : "V110",
			"Role/XiaoYaoJumpHit" : "V110",
			"Role/XiaoYaoJumpPressHit1" : "",
			"Role/XiaoYaoJumpPressHit2" : "",
			"Role/XiaoYaoSkill1" : "",
			"Role/XiaoYaoSkill2" : "",
			"Role/XiaoYaoSkill3" : "",
			"Role/XiaoYaoSkill4_1" : "",
			"Role/XiaoYaoSkill4_2" : "",
			"Role/XiaoYaoSkill5_1" : "V103",
			"Role/XiaoYaoSkill5_2" : "V103",
			"Role/XiaoYaoSkill5_3" : "V103",
			"Role/XiaoYaoSkill6" : "V103",
			"Role/XiaoYaoSkill7_1" : "",
			"Role/XiaoYaoSkill7_2" : "",
			"Role/XiaoYaoSkill8_1" : "",
			"Role/XiaoYaoSkill8_2" : "",
			"Role/XiaoYaoSkill9" : "",
			"Role/XiaoYaoSkill10" : "V103",
			"Role/XiaoYaoSkillStatus" : "V103",
			
			"Role/XiaoYaoWeapon" : "",
			"Role/XiaoYaoShoulder" : "",
			"Role/XiaoYaoHead" : "",
			"Role/XiaoYaoFrontHand" : "",
			"Role/XiaoYaoFrontHair" : "",
			"Role/XiaoYaoClothes" : "",
			"Role/XiaoYaoBackHand" : "",
			"Role/XiaoYaoBackHair" : "",
			
			"Role/XiaoYaoWeapon01" : "",
			"Role/XiaoYaoShoulder01" : "",
			"Role/XiaoYaoHead01" : "",
			"Role/XiaoYaoFrontHand01" : "",
			"Role/XiaoYaoClothes01" : "",
			"Role/XiaoYaoBackHand01" : "",
			
			"Role/XiaoYaoWeapon02" : "",
			"Role/XiaoYaoShoulder02" : "",
			"Role/XiaoYaoHead02" : "",
			"Role/XiaoYaoFrontHand02" : "",
			"Role/XiaoYaoClothes02" : "",
			"Role/XiaoYaoBackHand02" : "",
			
			"Role/XiaoYaoWeapon03" : "",
			"Role/XiaoYaoShoulder03" : "",
			"Role/XiaoYaoHead03" : "",
			"Role/XiaoYaoFrontHand03" : "",
			"Role/XiaoYaoClothes03" : "",
			"Role/XiaoYaoBackHand03" : "",
			
			"Role/XiaoYaoWeapon04" : "V109",
			"Role/XiaoYaoShoulder04" : "V109",
			"Role/XiaoYaoHead04" : "V109",
			"Role/XiaoYaoFrontHand04" : "V109",
			"Role/XiaoYaoClothes04" : "V109",
			"Role/XiaoYaoBackHand04" : "V109",
			
			"Role/XiaoYaoWeapon05" : "V119",
			"Role/XiaoYaoShoulder05" : "V119",
			"Role/XiaoYaoHead05" : "V119",
			"Role/XiaoYaoFrontHair05" : "V119",
			"Role/XiaoYaoFrontHand05" : "V119",
			"Role/XiaoYaoClothes05" : "V119",
			"Role/XiaoYaoBackHair05" : "V119",
			"Role/XiaoYaoBackHand05" : "V119",
			
			"Role/XiaoYaoBackHandFashion01" : "V110",
			"Role/XiaoYaoClothesFashion01" : "V110",
			"Role/XiaoYaoFrontHandFashion01" : "V110",
			"Role/XiaoYaoHeadFashion01" : "V110",
			"Role/XiaoYaoFrontHairFashion01" : "V110",
			"Role/XiaoYaoShoulderFashion01" : "V110",
			"Role/XiaoYaoWeaponFashion01" : "V110",
			
			"Role/XiaoYaoBackHandFashion02" : "V114",
			"Role/XiaoYaoClothesFashion02" : "V114",
			"Role/XiaoYaoFrontHandFashion02" : "V114",
			"Role/XiaoYaoBackHairFashion02" : "V114",
			"Role/XiaoYaoHeadFashion02" : "V114",
			"Role/XiaoYaoFrontHairFashion02" : "V114",
			"Role/XiaoYaoShoulderFashion02" : "V114",
			"Role/XiaoYaoWeaponFashion02" : "V114",
			
			"Role/XiaoYaoBackHandFashion03" : "V116",
			"Role/XiaoYaoClothesFashion03" : "V116",
			"Role/XiaoYaoFrontHandFashion03" : "V116",
			"Role/XiaoYaoBackHairFashion03" : "V116",
			"Role/XiaoYaoHeadFashion03" : "V116",
			"Role/XiaoYaoFrontHairFashion03" : "V116",
			"Role/XiaoYaoShoulderFashion03" : "V116",
			"Role/XiaoYaoWeaponFashion03" : "V116",
			
			"Role/XiaoYaoBackHandFashion04" : "V118",
			"Role/XiaoYaoClothesFashion04" : "V118",
			"Role/XiaoYaoFrontHandFashion04" : "V118",
			"Role/XiaoYaoBackHairFashion04" : "V118",
			"Role/XiaoYaoHeadFashion04" : "V118",
			"Role/XiaoYaoFrontHairFashion04" : "V118",
			"Role/XiaoYaoShoulderFashion04" : "V118",
			"Role/XiaoYaoWeaponFashion04" : "V118",
			
			"Role/XiaoYaoBackHandFashion05" : "V120",
			"Role/XiaoYaoClothesFashion05" : "V120",
			"Role/XiaoYaoFrontHandFashion05" : "V120",
			"Role/XiaoYaoBackHairFashion05" : "V120",
			"Role/XiaoYaoHeadFashion05" : "V120",
			"Role/XiaoYaoFrontHairFashion05" : "V120",
			"Role/XiaoYaoShoulderFashion05" : "V120",
			"Role/XiaoYaoWeaponFashion05" : "V120",
			
			"Role/XiaoYaoBackHandFashion06" : "V122",
			"Role/XiaoYaoClothesFashion06" : "V122",
			"Role/XiaoYaoFrontHandFashion06" : "V122",
			"Role/XiaoYaoBackHairFashion06" : "V122",
			"Role/XiaoYaoHeadFashion06" : "V122",
			"Role/XiaoYaoFrontHairFashion06" : "V122",
			"Role/XiaoYaoShoulderFashion06" : "V122",
			"Role/XiaoYaoWeaponFashion06" : "V122",
			
			"Role/XiaoYaoCommonHit1Fashion01" : "V110",
			"Role/XiaoYaoCommonHit2Fashion01" : "V110",
			"Role/XiaoYaoCommonHit3Fashion01" : "V110",
			"Role/XiaoYaoCommonHit4Fashion01" : "V110",
			"Role/XiaoYaoRunHitFashion01" : "V110",
			"Role/XiaoYaoJumpHitFashion01" : "V110",
			"Role/XiaoYaoJumpPressHit1Fashion01" : "V110",
			"Role/XiaoYaoJumpPressHit2Fashion01" : "V110",
			
			"Role/QiGai" : "",
			"Role/QiGaiCommonHit1" : "",
			"Role/QiGaiSkill1" : "",
			
			"Role/ShiFangXiuCai" : "",
			"Role/ShiFangXiuCaiCommonHit1" : "",
			"Role/ShiFangXiuCaiSkill1" : "",
			
			"Role/BuTongLaoRen" : "",
			"Role/BuTongLaoRenCommonHit1" : "",
			"Role/BuTongLaoRenSkill1_1" : "",
			"Role/BuTongLaoRenSkill1_2" : "",
			
			"Role/BiChiFuRen" : "",
			"Role/BiChiFuRenCommonHit1" : "",
			"Role/BiChiFuRenSkill1" : "",
			
			"Role/QiangDao" : "",
			"Role/QiangDaoCommonHit1" : "",
			"Role/QiangDaoSkill1" : "",
			
			"Role/HeiYiCiKe" : "",
			"Role/HeiYiCiKeCommonHit1" : "",
			"Role/HeiYiCiKeSkill1" : "",
			
			"Role/DouLiJianKe" : "",
			"Role/DouLiJianKeCommonHit1" : "",
			"Role/DouLiJianKeSkill1" : "",
			
			"Role/JiuGui" : "",
			"Role/JiuGuiCommonHit1" : "",
			"Role/JiuGuiCommonHit2" : "",
			"Role/JiuGuiSkill1_1" : "",
			"Role/JiuGuiSkill1_2" : "",
			"Role/JiuGuiSkill1_3" : "",
			"Role/JiuGuiSkill1_4" : "",
			"Role/JiuGuiSkill1_5" : "",
			
			"Role/HaMaGuai" : "",
			"Role/HaMaGuaiCommonHit1" : "",
			"Role/HaMaGuaiSkill1" : "",
			
			"Role/YinYangZhenRen" : "",
			"Role/YinYangZhenRenCommonHit1" : "",
			"Role/YinYangZhenRenSkill1" : "",
			"Role/YinYangZhenRenSkill2" : "",
			
			"Role/FengLiuDaoRen" : "",
			"Role/FengLiuDaoRenCommonHit1" : "",
			"Role/FengLiuDaoRenSkill1" : "",
			
			"Role/HongLianSanRen" : "",
			"Role/HongLianSanRenCommonHit1" : "",
			"Role/HongLianSanRenCommonHit2" : "",
			"Role/HongLianSanRenSkill1" : "",
			
			"Role/XiaoDaoShi" : "",
			"Role/XiaoDaoShiCommonHit1" : "",
			"Role/XiaoDaoShiSkill1_1" : "",
			"Role/XiaoDaoShiSkill1_2" : "",
			
			"Role/XiaoDaoGu" : "",
			"Role/XiaoDaoGuCommonHit1" : "",
			"Role/XiaoDaoGuSkill1_1" : "",
			"Role/XiaoDaoGuSkill1_2" : "",
			
			"Role/XiaoWuYa" : "",
			"Role/XiaoWuYaCommonHit1" : "",
			"Role/XiaoWuYaSkill1_1" : "",
			"Role/XiaoWuYaSkill1_2" : "",
			
			"Role/XiaoShuJing" : "",
			"Role/XiaoShuJingCommonHit1" : "",
			"Role/XiaoShuJingSkill1_1" : "",
			"Role/XiaoShuJingSkill1_2" : "",
			"Role/XiaoShuJingSkill1_3" : "",
			
			"Role/SuoMingGuHun" : "V103",
			"Role/SuoMingGuHunCommonHit1" : "V103",
			"Role/SuoMingGuHunSkill1" : "V103",
			
			"Role/JianMoWangHun" : "V103",
			"Role/JianMoWangHunCommonHit1" : "V103",
			"Role/JianMoWangHunSkill1" : "V103",
			"Role/JianMoWangHunSkill2_1" : "V103",
			"Role/JianMoWangHunSkill2_2" : "V103",
			
			"Role/JiangShi" : "V104",
			"Role/JiangShiCommonHit1" : "V104",
			"Role/JiangShiSkill1" : "V104",
			
			"Role/XiaoHuoMo" : "V105",
			"Role/XiaoHuoMoCommonHit1" : "V105",
			"Role/XiaoHuoMoSkill1_1" : "V105",
			"Role/XiaoHuoMoSkill1_2" : "V105",
			
			"Role/MingHuoFenShen" : "V105",
			"Role/MingHuoFenShenCommonHit1" : "V105",
			"Role/MingHuoFenShenSkill1_1" : "V105",
			"Role/MingHuoFenShenSkill1_2" : "V105",
			"Role/MingHuoFenShenSkill2" : "V105",
			"Role/MingHuoFenShenSkill3" : "V105",
			"Role/MingHuoFenShenSkill4" : "V105",
			
			"Role/KuLouYeGui" : "V108",
			"Role/KuLouYeGuiCommonHit1" : "V108",
			"Role/KuLouYeGuiSkill1_1" : "V108",
			"Role/KuLouYeGuiSkill1_2" : "V108",
			"Role/KuLouYeGuiSkill1_3" : "V108",
			
			"Role/SeZhongEGui" : "V108",
			"Role/SeZhongEGuiCommonHit1" : "V108",
			"Role/SeZhongEGuiSkill1_1" : "V108",
			"Role/SeZhongEGuiSkill1_2" : "V108",
			"Role/SeZhongEGuiSkill2" : "V108",
			
			"Role/EMoQuan" : "V109",
			"Role/EMoQuanCommonHit1" : "V109",
			"Role/EMoQuanSkill1_1" : "V109",
			"Role/EMoQuanSkill1_2" : "V109",
			"Role/EMoQuanSkill1_3" : "V109",
			
			"Role/LeiChenDianNu" : "V109",
			"Role/LeiChenDianNuCommonHit1" : "V109",
			"Role/LeiChenDianNuSkill1_1" : "V109",
			"Role/LeiChenDianNuSkill1_2" : "V109",
			"Role/LeiChenDianNuSkill1_3" : "V109",
			"Role/LeiChenDianNuSkill2_1" : "V109",
			"Role/LeiChenDianNuSkill2_2" : "V109",
			"Role/LeiChenDianNuSkill2_3" : "V109",
			
			"Role/TuFu" : "V110",
			"Role/TuFuCommonHit1" : "V110",
			"Role/TuFuSkill1_1" : "V110",
			"Role/TuFuSkill1_2" : "V110",
			"Role/TuFuSkill1_3" : "V110",
			
			"Role/ChiNan" : "V110",
			"Role/ChiNanCommonHit1" : "V110",
			"Role/ChiNanSkill1_1" : "V110",
			"Role/ChiNanSkill1_2" : "V110",
			"Role/ChiNanSkill1_3" : "V110",
			"Role/ChiNanSkill1_4" : "V110",
			"Role/ChiNanSkill1_5" : "V110",
			"Role/ChiNanSkill2_1" : "V110",
			"Role/ChiNanSkill2_2" : "V110",
			"Role/ChiNanSkill3" : "V110",
			
			"Role/YuanNv" : "V110",
			"Role/YuanNvCommonHit1" : "V110",
			"Role/YuanNvCommonHit2" : "V110",
			"Role/YuanNvCommonHit3" : "V110",
			"Role/YuanNvSkill1_1" : "V110",
			"Role/YuanNvSkill1_2" : "V110",
			"Role/YuanNvSkill1_3" : "V110",
			"Role/YuanNvSkill2_1" : "V110",
			
			"Role/XiaoEMo" : "V115",
			"Role/XiaoEMoCommonHit1_1" : "V115",
			"Role/XiaoEMoCommonHit1_2" : "V115",
			"Role/XiaoEMoSkill1_1" : "V115",
			"Role/XiaoEMoSkill1_2" : "V115",
			"Role/XiaoEMoSkill1_3" : "V115",
			
			"Role/TanDeWuYan_01" : "V115",
			"Role/TanDeWuYanCommonHit1_01" : "V115",
			"Role/TanDeWuYanSkill1_1_01" : "V115",
			"Role/TanDeWuYanSkill1_2_01" : "V115",
			"Role/TanDeWuYanSkill2_01" : "V115",
			
			"Role/TanDeWuYan_02" : "V115",
			"Role/TanDeWuYanCommonHit1_02" : "V115",
			"Role/TanDeWuYanSkill1_1_02" : "V115",
			"Role/TanDeWuYanSkill1_2_02" : "V115",
			"Role/TanDeWuYanSkill2_02" : "V115",
			
			"Role/HeTong" : "V117",
			"Role/HeTongCommonHit1" : "V117",
			"Role/HeTongSkill1" : "V117",
			
			"Role/TieJiangBaiDu" : "V117",
			"Role/TieJiangBaiDuCommonHit1" : "V117",
			"Role/TieJiangBaiDuSkill1_1" : "V117",
			"Role/TieJiangBaiDuSkill1_2" : "V117",
			"Role/TieJiangBaiDuSkill2" : "V117",
			
			"Role/XiaoGui" : "V119",
			"Role/XiaoGuiCommonHit1" : "V119",
			"Role/XiaoGuiSkill1" : "V119",
			
			"Role/JueXiuJiaoQiao" : "V119",
			"Role/JueXiuJiaoQiaoCommonHit1" : "V119",
			"Role/JueXiuJiaoQiaoSkill1_1" : "V119",
			"Role/JueXiuJiaoQiaoSkill1_2" : "V119",
			"Role/JueXiuJiaoQiaoSkill1_3" : "V119",
			"Role/JueXiuJiaoQiaoSkill2" : "V119",
			
			"Role/XiaoGeJi" : "V121",
			"Role/XiaoGeJiCommonHit1" : "V121",
			"Role/XiaoGeJiSkill1_1" : "V121",
			"Role/XiaoGeJiSkill1_2" : "V121",
			
			"Role/HeiYiShaShou" : "V121",
			"Role/HeiYiShaShouCommonHit1_1" : "V121",
			"Role/HeiYiShaShouCommonHit1_2" : "V121",
			"Role/HeiYiShaShouSkill1" : "V121",
			
			"Role/XiaoMianJunZi" : "V121",
			"Role/XiaoMianJunZiCommonHit1" : "V121",
			"Role/XiaoMianJunZiSkill1" : "V121",
			
			"Role/FunnyBossOne" : "V122",
			"Role/FunnyBossOneCommonHit1" : "V122",
			"Role/FunnyBossOneSkill1_1" : "V122",
			"Role/FunnyBossOneSkill1_2" : "V122",
			"Role/FunnyBossOneSkill2_1" : "V122",
			"Role/FunnyBossOneSkill2_2" : "V122",
			"Role/FunnyBossOneSkill2_3" : "V122",
			
			"Role/FunnyBossTwo" : "V122",
			"Role/FunnyBossTwoCommonHit1" : "V122",
			"Role/FunnyBossTwoSkill1" : "V122",
			"Role/FunnyBossTwoSkill2_1" : "V122",
			"Role/FunnyBossTwoSkill2_2" : "V122",
			"Role/FunnyBossTwoSkill2_3" : "V122",
			
			"Role/FunnyBossThree" : "V122",
			"Role/FunnyBossThreeCommonHit1" : "V122",
			"Role/FunnyBossThreeSkill1_1" : "V122",
			"Role/FunnyBossThreeSkill1_2" : "V122",
			"Role/FunnyBossThreeSkill1_3" : "V122",
			"Role/FunnyBossThreeSkill2_1" : "V122",
			"Role/FunnyBossThreeSkill2_2" : "V122",
			"Role/FunnyBossThreeSkill2_3" : "V122",
			"Role/FunnyBossThreeSkill2_4" : "V122",
			
			"Role/FunnyBossFour" : "V122",
			"Role/FunnyBossFourCommonHit1_1" : "V122",
			"Role/FunnyBossFourCommonHit1_2" : "V122",
			"Role/FunnyBossFourSkill1" : "V122",
			"Role/FunnyBossFourSkill2_1" : "V122",
			"Role/FunnyBossFourSkill2_2" : "V122",
			"Role/FunnyBossFourSkill2_3" : "V122",
			
			"Role/TuYe" : "V123",
			"Role/TuYeCommonHit1" : "V123",
			"Role/TuYeSkill1_1" : "V123",
			"Role/TuYeSkill1_2" : "V123",
			"Role/TuYeSkill2_1" : "V123",
			"Role/TuYeSkill2_2" : "V123",
			"Role/TuYeSkill2_3" : "V123",
			"Role/TuYeSkill2_4" : "V123",
			"Role/TuYeSkill2_5" : "V123",
			"Role/TuYeSkill2_6" : "V123",
			
			"Role/TuMei" : "V123",
			"Role/TuMeiCommonHit1" : "V123",
			"Role/TuMeiSkill1" : "V123",
			"Role/TuMeiSkill2" : "V123"
		};
	}
}